name: Java CI with PostgreSQL

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: db_test
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Setup OpenJDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: maven

      - name: Create database
        run: |
          echo "Create database"
          PGPASSWORD=123 psql -h localhost -U postgres -W -c 'CREATE DATABASE "fullstack_auth";'  

      - name: Run Tests
        run: |
          mvn --batch-mode --update-snapshots package
